// research/species.json -> site/fishes.js, downloading each Commons image into site/assets/fish/
import fs from 'node:fs'; import path from 'node:path'; import sharp from 'sharp';
const root = path.resolve(new URL('..', import.meta.url).pathname);
const species = JSON.parse(fs.readFileSync(path.join(root, 'research/species.json'), 'utf8'));
const dir = path.join(root, 'site/assets/fish'); fs.mkdirSync(dir, { recursive: true });
const UA = 'AegeanSeaGiftSite/1.0 (personal project; contact via github jonathan-politzki)';
const sleep = ms => new Promise(r => setTimeout(r, ms));
// Commons rate-limits anonymous API calls (HTTP 429); wait and retry rather than dropping the entry.
async function getJSON(api, tries = 6) {
  for (let i = 0; i < tries; i++) {
    const r = await fetch(api, { headers: { 'User-Agent': UA } });
    if (r.status === 429) { const wait = (parseInt(r.headers.get('retry-after') || '0', 10) || 10) + 2; console.log('rate-limited, waiting', wait, 's'); await sleep(wait * 1000); continue; }
    if (!r.ok) throw new Error('HTTP ' + r.status);
    return r.json();
  }
  throw new Error('rate-limited after ' + tries + ' tries');
}
async function commonsUrl(filePage) {
  const title = decodeURIComponent(filePage.split('/wiki/')[1] || '');
  if (!title) return null;
  const api = `https://commons.wikimedia.org/w/api.php?action=query&titles=${encodeURIComponent(title)}&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=1200&format=json`;
  const j = await getJSON(api);
  const page = Object.values(j.query.pages)[0]; const ii = page.imageinfo?.[0]; if (!ii) return null;
  const m = ii.extmetadata || {};
  return { url: ii.thumburl || ii.url, author: (m.Artist?.value || '').replace(/<[^>]+>/g, '').trim(), license: m.LicenseShortName?.value || '' };
}
for (const f of species) {
  if (!f.image?.file_page) continue;
  const out = path.join(dir, `${f.id}.jpg`);
  try {
    const info = await commonsUrl(f.image.file_page);
    if (!info) { console.log('no imageinfo', f.id); continue; }
    if (!fs.existsSync(out)) {
      const r = await fetch(info.url, { headers: { 'User-Agent': UA } });
      if (!r.ok) { console.log('download failed', f.id, r.status); continue; }
      const buf = Buffer.from(await r.arrayBuffer());
      await sharp(buf).resize({ width: 1000, withoutEnlargement: true }).flatten({ background: '#eae3d2' }).jpeg({ quality: 82, mozjpeg: true }).toFile(out);
    }
    f.image.local = `assets/fish/${f.id}.jpg`;
    if (info.author && !f.image.author) f.image.author = info.author;
    if (info.license && !f.image.license) f.image.license = info.license;
    console.log('ok', f.id, info.license, '|', info.author.slice(0, 40));
  } catch (e) { console.log('error', f.id, e.message); }
  await sleep(1200);
}
fs.writeFileSync(path.join(root, 'site/fishes.js'), '/* generated by tools/build-fishes.mjs from research/species.json */\nwindow.AEGEAN_FISHES = ' + JSON.stringify(species, null, 1) + ';\n');
console.log('wrote site/fishes.js');
